export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS'
export const GET_INGREDIENTS_ERROR = 'GET_INGREDIENTS_ERROR'
export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST'


export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'


export const ADD_BUN = 'ADD_BUN'
export const DELETE_BUN = 'DELETE_BUN'


export const INGREDIENT_OPEN_MODAL = 'INGREDIENT_OPEN_MODAL'
export const INGREDIENT_CLOSE_MODAL = 'INGREDIENT_CLOSE_MODAL'

export const INGREDIENT_COUNT_PLUS = 'INGREDIENT_COUNT_PLUS'
export const INGREDIENT_COUNT_MINUS = 'INGREDIENT_COUNT_MINUS'

export const CLOSE_ORDER = 'CLOSE_ORDER'
export const GET_ORDER = 'GET_ORDER'
export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_ERROR = 'GET_ORDER_ERROR'

export const CONSTRUCTOR_MOVE = 'CONSTRUCTOR_MOVE'
