export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS'
export const GET_INGREDIENTS_ERROR = 'GET_INGREDIENTS_ERROR'
export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST'


export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'


export const ADD_BUN = 'ADD_BUN'
export const DELETE_BUN = 'DELETE_BUN'


export const INGREDIENT_OPEN_MODAL = 'INGREDIENT_OPEN_MODAL'
export const INGREDIENT_CLOSE_MODAL = 'INGREDIENT_CLOSE_MODAL'

export const INGREDIENT_COUNT_PLUS = 'INGREDIENT_COUNT_PLUS'
export const INGREDIENT_COUNT_MINUS = 'INGREDIENT_COUNT_MINUS'

export const CLOSE_ORDER = 'CLOSE_ORDER'
export const GET_ORDER = 'GET_ORDER'
export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_ERROR = 'GET_ORDER_ERROR'

export const CONSTRUCTOR_MOVE = 'CONSTRUCTOR_MOVE'


export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_REQUEST_SUCCESS = "FORGOT_PASSWORD_REQUEST_SUCCESS";
export const FORGOT_PASSWORD_REQUEST_ERROR = "FORGOT_PASSWORD_REQUEST_ERROR";
export const FORGOT_PASSWORD_RESET = "FORGOT_PASSWORD_RESET";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_ERROR = "LOGIN_REQUEST_ERROR";
export const LOGIN_STATE_RESET = "LOGIN_STATE_RESET";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_REQUEST_SUCCESS = "LOGOUT_REQUEST_SUCCESS";
export const LOGOUT_REQUEST_ERROR = "LOGOUT_REQUEST_ERROR";
export const LOGOUT_STATE_RESET = "LOGOUT_STATE_RESET";

export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_REQUEST_SUCCESS = "PROFILE_REQUEST_SUCCESS";
export const PROFILE_REQUEST_ERROR = "PROFILE_REQUEST_ERROR";
export const PROFILE_STATE_RESET = "PROFILE_STATE_RESET";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_REQUEST_SUCCESS = "RESET_PASSWORD_REQUEST_SUCCESS";
export const RESET_PASSWORD_REQUEST_ERROR = "RESET_PASSWORD_REQUEST_ERROR";
export const RESET_PASSWORD_INITIAL = "RESET_PASSWORD_INITIAL";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_REQUEST_SUCCESS = "SIGN_UP_REQUEST_SUCCESS";
export const SIGN_UP_REQUEST_ERROR = "SIGN_UP_REQUEST_ERROR"

export const UPDATE_TOKEN_REQUEST = "UPDATE_TOKEN_REQUEST";
export const UPDATE_TOKEN_REQUEST_SUCCESS = "UPDATE_TOKEN_REQUEST_SUCCESS";
export const UPDATE_TOKEN_REQUEST_ERROR = "UPDATE_TOKEN_REQUEST_ERROR";

export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";